### ISSUE TITLE
Blank screen on Ubuntu 16.04

### ISSUE THREAD

**Issue by curtpm** [stevelacy/msi-keyboard-gui#10]
When i use either the prebuilt binary or build from source after it starts all i see is an Empty grey window.

**Comment by stephenlacy** [comment]
What is your node version? v6+ should work

Please also check this: https://github.com/stevelacy/msi-keyboard-gui/issues/2

**Comment by curtpm** [comment]
```
nodejs --version
v6.6.0
```

**Comment by stephenlacy** [comment]
What are the console errors? Ctrl + Shift + i

**Comment by curtpm** [comment]
'ctrl + shift + i' doesn't do anything when the window is in focus.

**Comment by stephenlacy** [comment]
Did you try the comments in #2 and verify the required dependencies?

**Comment by curtpm** [comment]
that fixed it ! thanks!
