### ISSUE TITLE
Trying on Hackintosh OS X 10.11.6

### ISSUE THREAD

**Issue by jbmaxwell** [stevelacy/msi-keyboard-gui#14]
I disabled system integrity protection [(info)](www.imore.com/el-capitan-system-integrity-protection-helps-keep-malware-away) and ran from sudo, but I still get the "try from sudo" error. Any ideas what I might check?

The gui does come up, btw.

**Comment by stephenlacy** [comment]
This is not designed or supported for non Linux systems. The application does not find the needed mapper to the USB HID device.

**Comment by jbmaxwell** [comment]
So no thoughts on where I might look to patch/hack it?

**Comment by stephenlacy** [comment]
You would need to get a list of the HID devices attached to the machine.
http://stackoverflow.com/questions/6477385/raw-access-to-hid-devices-in-os-x

**Comment by jbmaxwell** [comment]
Of course, yes. I can look into that further... not insurmountable, by any mean... Can you point to a particular part of your code that deals with the device Ids? 
Much appreciated. (The red/orange is kinda cool, but it gets "tired" pretty quick... and I'd like to kill it for battery purposes.)

**Comment by stephenlacy** [comment]
The main line for retrieving and initiating the keyboard is here: https://github.com/stevelacy/msi-keyboard/blob/master/lib/findKeyboard.js#L7

And sending the feature report to the hid device: https://github.com/stevelacy/msi-keyboard/blob/master/lib/setColor.js#L24

**Comment by jbmaxwell** [comment]
Right, okay. So you instantiate an HID object with the Ids... I'll see what I can do. Thanks!

**Comment by stephenlacy** [comment]
Quick question, could you do this:

```js
var HID = require('node-hid');
var devices = HID.devices();
console.log(devices);
```
And post the output?

**Comment by jbmaxwell** [comment]
[ { vendorId: 1452,
    productId: 782,
    path: 'IOService:/AppleACPIPlatformExpert/PS2K/ps2controller/ApplePS2Controller/ApplePS2KeyboardDevice/ApplePS2Keyboard/IOHIDKeyboardDevice',
    serialNumber: '',
    manufacturer: 'Apple',
    product: 'Keyboard',
    release: 0,
    interface: -1,
    usagePage: 1,
    usage: 6 },
  { vendorId: 1452,
    productId: 613,
    path: 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC@14/XHC@14000000/HS01@14100000/Magic Trackpad 2@14100000/Actuator@2/AppleUSBTopCaseHIDDriver@14100000,2',
    serialNumber: 'CC260450KWDG61CA0',
    manufacturer: 'Apple Inc.',
    product: 'Magic Trackpad 2',
    release: 2052,
    interface: -1,
    usagePage: 65280,
    usage: 13 },
  { vendorId: 1452,
    productId: 613,
    path: 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC@14/XHC@14000000/HS01@14100000/Magic Trackpad 2@14100000/Trackpad / Boot@1/AppleUSBTopCaseHIDDriver@14100000,1',
    serialNumber: 'CC260450KWDG61CA0',
    manufacturer: 'Apple Inc.',
    product: 'Magic Trackpad 2',
    release: 2052,
    interface: -1,
    usagePage: 1,
    usage: 2 },
  { vendorId: 1452,
    productId: 613,
    path: 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC@14/XHC@14000000/HS01@14100000/Magic Trackpad 2@14100000/Accelerometer@3/AppleUSBTopCaseHIDDriver@14100000,3',
    serialNumber: 'CC260450KWDG61CA0',
    manufacturer: 'Apple Inc.',
    product: 'Magic Trackpad 2',
    release: 2052,
    interface: -1,
    usagePage: 65280,
    usage: 3 },
  { vendorId: 1452,
    productId: 782,
    path: 'IOService:/AppleACPIPlatformExpert/PS2K/ps2controller/ApplePS2Controller/ApplePS2MouseDevice/ApplePS2SmartTouchpad/IOHIDPointingDevice',
    serialNumber: '',
    manufacturer: 'Apple',
    product: 'Trackpad',
    release: 4,
    interface: -1,
    usagePage: 1,
    usage: 2 },
  { vendorId: 1452,
    productId: 613,
    path: 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC@14/XHC@14000000/HS01@14100000/Magic Trackpad 2@14100000/Device Management@0/AppleUSBTopCaseHIDDriver@14100000,0',
    serialNumber: 'CC260450KWDG61CA0',
    manufacturer: 'Apple Inc.',
    product: 'Magic Trackpad 2',
    release: 2052,
    interface: -1,
    usagePage: 65280,
    usage: 11 } ]

**Comment by stephenlacy** [comment]
The keyboard is not listed. What MSI laptop is this?

**Comment by jbmaxwell** [comment]
Yeah, it's a Ghost Pro GS60 6QE, but I think I gave up on the backlight control when it appeared that the Hackintosh uses ApplePS2Keyboard.kext to run it... so it's not USB as far as the system is concerned. Honestly, I don't understand what's up with that. Maybe some kind of emulation?... not sure.

**Comment by stephenlacy** [comment]
Nice, I have that laptop as well. It sounds like apple uses a keyboard interface for all raw hid devices with a keyboard type.
If your keyboard stays on after reboot you could turn it on in linux or windows and then reboot into apple. Quite a hassle, but it might work

**Comment by jbmaxwell** [comment]
hmm... can't remember, but I think it might stay on. Will check it out at some point. Thanks for looking into it.

**Comment by AutinMitra** [comment]
msi-keyboard works on MacOS by using SmartTouchPad from [https://osxlatitude.com/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/](url). The driver I believe is a port from linux, which could explain why it works rather than applePS2 (which does not support ELAN well)

**Comment by stephenlacy** [comment]
Thats good, can you write up a install/setup doc?

**Comment by AutinMitra** [comment]
The gui version doesn't work with OS X (I'm looking into it), but msi-keyboard is.

**Comment by stephenlacy** [comment]
I'm guessing it's due to compiling for a different version of node, or node-hid mismatch.

**Comment by AutinMitra** [comment]
so far, it's because of cp for mac being a bit different than it is for linux, where there is no -t option.

**Comment by AutinMitra** [comment]
yup, its a node-hid mismatch (but electron 1.7.9 does work)

**Comment by stephenlacy** [comment]
Tested the latest changes on macos :smile: 
Let me know if the latest works for you, if not I'll re-open

**Comment by erikbdev** [comment]
> msi-keyboard works on MacOS by using SmartTouchPad

This does not affect anything thats related to the colors since MSI has the rgb colors separated into this USB called "MSI EPF USB". 
>Let me know if the latest works for you, if not I'll re-open

I used the latest release of msi-keyboard-gui but the colors don't change. The "node-hid mismatch" still happens. I will see if I can fix for macOS. I'm on node 8.14.1.

**Comment by erikbdev** [comment]
> node-hid mismatch" still happens

Nevermind. It does not say "node_module_mismatch" anymore, but the colors does not change.
