### ISSUE TITLE
blank window when i run the gui

### ISSUE THREAD

**Issue by pariosa** [stevelacy/msi-keyboard-gui#24]
### Issue

When i run npm start i get an electron window, but it is completely empty 

http://i.imgur.com/UWwLMpc.png

### System versions: Ubuntu 16.04.1

```
nodejs:v6.9.4
npm:3.10.10
libusb:2:0.1.12-28
```

**Comment by pariosa** [comment]
[msi-keyboard-gui] npm start                                              

> msi-keyboard-gui@0.1.2 start /home/[user]/msi-keyboard-gui
> electron-rebuild && electron .

✔ Rebuild Complete
^C
[msi-keyboard-gui] node -v                                               
v6.9.4
[msi-keyboard-gui] npm -v                                                
3.10.10

**Comment by stephenlacy** [comment]
Thank you - this issue has been reported already: #2 #4 #5 #10 

What is the error in the dev console? <kbd>CTRL</kbd>+<kbd>Snift</kbd>+<kbd>i</kbd>
The error is node-hid's native module not getting loaded for electron. All the electron rebuild steps sometimes manage to get the ENV correct and build the native module.

**Comment by pariosa** [comment]
Hi! thanks for linking the proper issue resolutions, i was able to fix with this solution:
https://github.com/stevelacy/msi-keyboard-gui/issues/2#issuecomment-236030137

**Comment by stephenlacy** [comment]
Could you do this:
```
git pull
rm -rf node_modules
npm install
sudo npm start
```

I pushed changes which should fix the need to monkey patch the build

**Comment by pariosa** [comment]
that worked!
