### ISSUE TITLE
Bluish Screen with prebuilt binaries and failed to start from dev

### ISSUE THREAD

**Issue by EgamoPi** [stevelacy/msi-keyboard-gui#28]
### Issue

**Describe your issue, comment or suggestion**
Good morning, 
First of all thank you so much for giving us the opportunity to play with our keyboard on linux :3
However I have some problems -
With the prebuilt binairies : 
The app launches but with a bluish screen and on my terminal i have this message : Gtk-Message: Failed to load module "canberra-gtk-module"

With development : 
see the reportbug below.
 ### System versions:

```
nodejs:6.10.1
npm:3.10.10
libusb:


```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle msi-keyboard-gui@0.1.4~prestart: msi-keyboard-gui@0.1.4
6 silly lifecycle msi-keyboard-gui@0.1.4~prestart: no script for prestart, continuing
7 info lifecycle msi-keyboard-gui@0.1.4~start: msi-keyboard-gui@0.1.4
8 verbose lifecycle msi-keyboard-gui@0.1.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle msi-keyboard-gui@0.1.4~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/omega/msi-keyboard-gui/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle msi-keyboard-gui@0.1.4~start: CWD: /home/omega/msi-keyboard-gui
11 silly lifecycle msi-keyboard-gui@0.1.4~start: Args: [ '-c', 'npm run build:app && electron ./dist/app' ]
12 silly lifecycle msi-keyboard-gui@0.1.4~start: Returned: code: 1  signal: null
13 info lifecycle msi-keyboard-gui@0.1.4~start: Failed to exec start script
14 verbose stack Error: msi-keyboard-gui@0.1.4 start: `npm run build:app && electron ./dist/app`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid msi-keyboard-gui@0.1.4
16 verbose cwd /home/omega/msi-keyboard-gui
17 error Linux 3.16.0-4-amd64
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.10.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error msi-keyboard-gui@0.1.4 start: `npm run build:app && electron ./dist/app`
22 error Exit status 1
23 error Failed at the msi-keyboard-gui@0.1.4 start script 'npm run build:app && electron ./dist/app'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the msi-keyboard-gui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:app && electron ./dist/app
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs msi-keyboard-gui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls msi-keyboard-gui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

EDIT : I restarted the manipulation, and installed the libusb tools once more, so the first method still having the same error (bluish screen) and the second method now launches the same bluish screen and same terminal error (Failed to load module "canberra-gtk-module")

**Comment by stephenlacy** [comment]
What is the error when you launch the prebuilt binary and open the console? `Ctrl + Shift + i`
