### ISSUE TITLE
Successful Build Results in Blank View

### ISSUE THREAD

**Issue by TomSchober** [stevelacy/msi-keyboard-gui#33]
### Issue
npm install and sudo npm start continue without error.  Blank GUI results.

**Describe your issue, comment or suggestion**

### System versions:
```
MSI Model: GS63VR 7RF
nodejs: 6.11.5
npm: 3.10.10
libusb: libusb-dev is already the newest version (2:0.1.12-28)
```
![screenshot from 2017-11-03 11-06-42](https://user-images.githubusercontent.com/1459967/32380840-8e28654e-c087-11e7-95c0-1aa92732afd0.png)

**Comment by stephenlacy** [comment]
Use a prebuilt release https://github.com/stevelacy/msi-keyboard-gui/releases/tag/0.1.4

**Comment by TomSchober** [comment]
Yes the pre-built version works fine

**Comment by stephenlacy** [comment]
`npm run build:linux` should build and fix the module mismatch (the blank screen)

You would then run the built app from the dist folder
