### ISSUE TITLE
Blank GUI

### ISSUE THREAD

**Issue by demaniak** [stevelacy/msi-keyboard-gui#4]
Hi.

I build from source, and tried the pre-built binaries.
The app starts up with a blank GUI (off-black background).
And does nothing else.

Node Version: v4.4.7
Ubuntu 14.04 LTS

**Comment by stephenlacy** [comment]
Please follow any suggestions found here; https://github.com/stevelacy/msi-keyboard-gui/issues/2

**Comment by stephenlacy** [comment]
Any updates?

**Comment by demaniak** [comment]
Sorry, been a bit pressed with work projects, I will attempts the suggestions mentioned in #2 as soon as possible (probably over the weekend). 
Thanks :)

**Comment by demaniak** [comment]
Ok, looks like the issue is pretty much the same as hunted in #2 - I could not get it working, and while this looks nifty, it is unfortunately not high enough on my priority list to continue digging.
Closing this issue.

Keep up the nifty work sir, good luck.
