### ISSUE TITLE
Error executing 'npm start'

### ISSUE THREAD

**Issue by dsabalete** [stevelacy/msi-keyboard-gui#40]
### Issue

**I have cloned your repo and executed 'npm install' without errors. But when trying to run 'npm start', I get an error message like the one shown in the attached file. I have also tried to run it with 'sudo' without luck**

### System versions:

```
nodejs: v.6.13.1
npm: 3.10.10
libusb: 1.0.0
```
![captura de pantalla de 2018-03-16 22-35-54](https://user-images.githubusercontent.com/2525976/37546128-c4165ef2-296b-11e8-88fa-b16374d9e76a.png)

**Comment by stephenlacy** [comment]
There are several issues with this error, it is a node version mismatch.

#35 #38 #33 #30 #24 #18 #10 #5 #2

First try with node 8

**Comment by dsabalete** [comment]
+1
