### ISSUE TITLE
Nothing is shown in the GUI

### ISSUE THREAD

**Issue by kalsia** [stevelacy/msi-keyboard-gui#5]
Good evening
As the title says, im getting a blank window after launching the tool  from the releases

Also tried the development one with npm but the result is the same

[http://imageshack.com/a/img922/3719/ZrCSPh.png](url)

Ubuntu 16.04 MSI GE62-6QD

**Comment by kalsia** [comment]
I just did a fresh install and all worked well this time... sorry about the closing/reopening

**Comment by stephenlacy** [comment]
No worries, I'm glad it is working for you!
