### ISSUE TITLE
Windows version didn't work.

### ISSUE THREAD

**Issue by comicsads** [stevelacy/msi-keyboard-gui#54]
### Issue

**Describe your issue, comment or suggestion**
My friend tried to download and run the exe and it gave him an error saying 
"cannot open device with vendor id 0x1770 and product id 0xff00
Did you try using sudo?"
He was using Windows 10 so that's why the sudo suggestion confused me.
He also tried running it as an administrator 

### System versions:
Windows 10

```
nodejs:
npm:
libusb:
```

**Comment by stephenlacy** [comment]
What laptop keyboard is he using? newer keyboards are not supported
