### ISSUE TITLE
Node-hid cannot seem to find my keyboard anymore: `cannot open device with vendor id 0x1770 and product id 0xff00`

### ISSUE THREAD

**Issue by bvobart** [stevelacy/msi-keyboard-gui#55]
### Issue

Hi, how has it been? I used to be able to use msi-keyboard and the GUI without any problems, but I recently reinstalled Ubuntu (same version, 18.04), and now I notice that msi-keyboard, or actually the underlying `node-hid`, can no longer seem to recognise my keyboard. I'm not sure if this might be a missing driver problem, but I was wondering whether you could help me shed light on this situation.

#### Symptoms:

Upon opening the GUI, I receive the error: `cannot open device with vendor id 0x1770 and product id 0xff00`

### System versions:

NodeJS: `8.11.4`
npm: `5.6.0`
libusb-dev: `2:0.1.12-31`
libusb-1.0-0-dev: `2:1.0.21-2`

### Troubleshooting steps

As a way of both trying to fix my problem, as well as helping to set up a set of standard troubleshooting questions and answers, which can then be placed in the ReadMe, I looked around to summarise the steps that can be taken to fix such a problem.

#### Did you use `sudo`?
Yes, I used `sudo` like there was no tomorrow.

#### Do you have the required versions `libusb-dev` and `libusb-1.0-0-dev` installed?

Yes, `dpkg -l | grep libusb` reports that versions `2:0.1.12-31` of `libusb-dev` and `2:1.0.21-2` of `libusb-1.0-0-dev` are installed. I presume these versions are high enough?

#### What is the output of [`msi-keyboard-hid-test`](https://github.com/stevelacy/msi-keyboard-hid-test)?:

Apparently it recognises my mouse, but no MSI or SteelSeries devices.

```
 ~/leds/msi-keyboard-hid-test > master > sudo node index.js
dev 46d / c332 : usage_page:10f8, usage:17e
dev 46d / c332 : usage_page:2d31, usage:2e31
[ { vendorId: 1133,
    productId: 49970,
    path: '/dev/hidraw0',
    serialNumber: '0E6336703330',
    manufacturer: 'Logitech',
    product: 'Gaming Mouse G502',
    release: 770,
    interface: 0,
    usagePage: 4344,
    usage: 382 },
  { vendorId: 1133,
    productId: 49970,
    path: '/dev/hidraw1',
    serialNumber: '0E6336703330',
    manufacturer: 'Logitech',
    product: 'Gaming Mouse G502',
    release: 770,
    interface: 1,
    usagePage: 11569,
    usage: 11825 } ]
```

#### What is the output of `lsusb`?

Interestingly, here we do see the desired 1770:ff00 device listed, though it does not have any name. That is consistent with the official `usb.ids` database however: https://usb-ids.gowdy.us/read/UD/1770

```
 ~/leds/msi-keyboard-hid-test > master > lsusb
Bus 002 Device 006: ID 1770:ff00  
Bus 002 Device 002: ID 8087:8000 Intel Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 8087:07dc Intel Corp. 
Bus 001 Device 005: ID 046d:c332 Logitech, Inc. 
Bus 001 Device 002: ID 8087:8008 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

#### Did you try purging and then reinstalling the package `xserver-xorg-input-all`?

Yes, didn't work.

**Comment by bvobart** [comment]
So as I was researching the cause of this issue, I noticed there was talk of two different types of USB detection libraries, namely `libusb` and `hidraw`, but did not think much of it. However, I just noticed [a remark made in the `node-hid` ReadMe](https://github.com/node-hid/node-hid/blob/master/README.md#selecting-driver-type). They state that from version 0.7.0 onwards, the `hidraw` driver is used by standard, while the last version to use the libusb driver as standard is 0.5.7.

With this in mind, I noticed that the `node-hid` version of `msi-keyboard-hid-test` is set to `^0.7.3`. Setting it to `0.5.7`, removing the node modules folder and re-`npm install`ing, I suddenly found it able to recognize my keyboard again:

```
 ~/leds/msi-keyboard-hid-test > master > sudo node index.js 
[ { vendorId: 6000,
    productId: 65280,
    path: '0002:0006:00',
    serialNumber: 'MSI EPF USB',
    manufacturer: 'MSI EPF USB',
    product: 'MSI EPF USB',
    release: 272,
    interface: 0 },
  { vendorId: 1133,
    productId: 49970,
    path: '0001:0005:00',
    serialNumber: '0E6336703330',
    manufacturer: 'Logitech',
    product: 'Gaming Mouse G502',
    release: 770,
    interface: 0 },
  { vendorId: 1133,
    productId: 49970,
    path: '0001:0005:01',
    serialNumber: '0E6336703330',
    manufacturer: 'Logitech',
    product: 'Gaming Mouse G502',
    release: 770,
    interface: 1 } ]
```

Moving to `msi-keyboard-gui`, I noticed that the version of `msi-keyboard` being required is `^0.3.1`, which upon further inspection depended on any (*) `node-hid` version. You did fix this and change it to `0.5.7` in version 0.4.1 of `msi-keyboard`, but did not update the GUI's dependencies accordingly, thus causing the wrong node-hid version to be installed when installing and running from source.

**Comment by stevelacy** [comment]
Thanks for debugging. I will fix the node-hid dependency and pin it on msi-keyboard

**Comment by stephenlacy** [comment]
Thanks for debugging, excellent issue and report.
I am on macos right now and am not able to build the release for windows/linux -- but I will build it shortly.

**Comment by stephenlacy** [comment]
Opening this until I push the release

**Comment by stephenlacy** [comment]
https://github.com/stevelacy/msi-keyboard-gui/releases/tag/v0.2.2
Published, let me know if it works for you, tested on debian.

**Comment by SaidMarar** [comment]
@stevelacy same problem with version 0.2.3 i remove it and install 0.2.2 and it works ! 0.2.3 does not support these changes

**Comment by ansidev** [comment]
@stevelacy Currently, you must set driver type for node-hid or it won't find the MSI Steel Series Keyboard.

```
HID.setDriverType('libusb');
```

Or you can find a way to find it with hidraw default driver.

**Comment by ansidev** [comment]
FYI
https://github.com/stevelacy/msi-keyboard/blob/master/lib/findKeyboard.js

**Comment by stephenlacy** [comment]
@ansidev PR welcome!
