### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Mohandevir** [stevelacy/msi-keyboard-gui#68]
Sorry... The issue is probably 18inches in front of the keyboard...

There is no msi-keyboard-gui command in the extracted folder... Can't install it on Mint 20.

Sorry if it's a dumb question... I'm no programmer, just a user.

Tried the npm start command and got this error log

[2020-07-30T22_38_21_366Z-debug.log](https://github.com/stevelacy/msi-keyboard-gui/files/5004100/2020-07-30T22_38_21_366Z-debug.log)

Thanks anyway.

**Comment by stephenlacy** [comment]
You downloaded the source code, try an older release with a binary: https://github.com/stevelacy/msi-keyboard-gui/releases/tag/v0.2.2

**Comment by Mohandevir** [comment]
Aaaah! I knew I was doing something wrong. Had to install a missing lib, but it's now working. Thanks!

**Comment by stephenlacy** [comment]
Awesome! if you hit any errors let me know and we can reopen the issue
