### ISSUE TITLE
Error  cannot open device on MacOS BigSur

### ISSUE THREAD

**Issue by jcodesss** [stevelacy/msi-keyboard-gui#69]
### Issue
when running showing this error msg
"Error

cannot open device with vendor id 0x1770 and product id 0xff00

Did you try using sudo?"
**Describe your issue, comment or suggestion**

### System versions:
Hackintosh MacOS Bigsur beta 3
HW: MSI GE62
```
nodejs: v12.16.1
npm: 6.14.7
libusb:
```

**Comment by stephenlacy** [comment]
Not supporting Beta OS at this point. Will accept a PR for future support.
