### ISSUE TITLE
Not Working Ubuntu 20.04

### ISSUE THREAD

**Issue by vpapaioannou** [stevelacy/msi-keyboard-gui#70]
### Issue

![Screenshot from 2020-09-29 18-48-42](https://user-images.githubusercontent.com/6065702/94624517-a0b3ab00-0284-11eb-9ce9-7dbb79d72cc5.png)

### System versions:

Ubuntu 20.04

**Comment by stephenlacy** [comment]
Check your error logs for the issue.
1. use sudo to build
2. install the build libraries for libudev.h
