### ISSUE TITLE
No support for GP75 9SD

### ISSUE THREAD

**Issue by Jullegaming04** [stevelacy/msi-keyboard-gui#75]
### Hi there i cannot use the software because it's saying TypeError: cannot open device with vendor id 0x1770 and product id 0xff00
can you add support for the device and yes i have tried everything i could find to get this to work but no i did not work

**Describe your issue, comment or suggestion**

### System versions:

```
nodejs:
npm:
libusb:
```

**Comment by stephenlacy** [comment]
Did you use sudo?

I am not adding support for any new devices.
